# Generated by Django 4.2.7 on 2023-11-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_bot_id_message_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_from_bot',
            field=models.BooleanField(default=False),
        ),
    ]
